<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260920210119 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE evaluation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, niveau VARCHAR(255) NOT NULL, libelle VARCHAR(255) DEFAULT NULL, date DATE NOT NULL, matiere VARCHAR(255) NOT NULL, isremuneration BOOLEAN DEFAULT NULL, periode_id INT DEFAULT NULL, enfant_id INT DEFAULT NULL, remuneration_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1323A575F384C1CF ON evaluation (periode_id)');
        $this->addSql('CREATE INDEX IDX_1323A575450D2529 ON evaluation (enfant_id)');
        $this->addSql('CREATE INDEX IDX_1323A5751D7E2A02 ON evaluation (remuneration_id)');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT FK_1323A575F384C1CF FOREIGN KEY (periode_id) REFERENCES periode (id)');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT FK_1323A575450D2529 FOREIGN KEY (enfant_id) REFERENCES enfant (id)');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT FK_1323A5751D7E2A02 FOREIGN KEY (remuneration_id) REFERENCES remuneration (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE evaluation DROP CONSTRAINT FK_1323A575F384C1CF');
        $this->addSql('ALTER TABLE evaluation DROP CONSTRAINT FK_1323A575450D2529');
        $this->addSql('ALTER TABLE evaluation DROP CONSTRAINT FK_1323A5751D7E2A02');
        $this->addSql('DROP TABLE evaluation');
    }
}
