<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260926134949 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE classe (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, niveau_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8F87BF96B3E9C81 ON classe (niveau_id)');
        $this->addSql('CREATE TABLE enfant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, periode_type VARCHAR(20) NOT NULL, evaluation_mode VARCHAR(20) NOT NULL, classe_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_34B70CA28F5EA509 ON enfant (classe_id)');
        $this->addSql('CREATE TABLE enfant_family_group (enfant_id INT NOT NULL, family_group_id INT NOT NULL, PRIMARY KEY (enfant_id, family_group_id))');
        $this->addSql('CREATE INDEX IDX_6A066A75450D2529 ON enfant_family_group (enfant_id)');
        $this->addSql('CREATE INDEX IDX_6A066A753CEE3234 ON enfant_family_group (family_group_id)');
        $this->addSql('CREATE TABLE evaluation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, niveau VARCHAR(255) NOT NULL, libelle VARCHAR(255) DEFAULT NULL, date DATE NOT NULL, matiere VARCHAR(255) NOT NULL, is_remuneration BOOLEAN DEFAULT NULL, periode_id INT DEFAULT NULL, enfant_id INT DEFAULT NULL, remuneration_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1323A575F384C1CF ON evaluation (periode_id)');
        $this->addSql('CREATE INDEX IDX_1323A575450D2529 ON evaluation (enfant_id)');
        $this->addSql('CREATE INDEX IDX_1323A5751D7E2A02 ON evaluation (remuneration_id)');
        $this->addSql('CREATE TABLE family_group (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE family_group_user (family_group_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (family_group_id, user_id))');
        $this->addSql('CREATE INDEX IDX_97035E463CEE3234 ON family_group_user (family_group_id)');
        $this->addSql('CREATE INDEX IDX_97035E46A76ED395 ON family_group_user (user_id)');
        $this->addSql('CREATE TABLE matiere (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE niveau (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE note (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, note DOUBLE PRECISION NOT NULL, denominateur DOUBLE PRECISION NOT NULL, coefficient DOUBLE PRECISION NOT NULL, date DATE NOT NULL, is_remuneration BOOLEAN DEFAULT NULL, libelle VARCHAR(255) DEFAULT NULL, enfant_id INT DEFAULT NULL, periode_id INT DEFAULT NULL, remuneration_id INT DEFAULT NULL, matiere_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CFBDFA14450D2529 ON note (enfant_id)');
        $this->addSql('CREATE INDEX IDX_CFBDFA14F384C1CF ON note (periode_id)');
        $this->addSql('CREATE INDEX IDX_CFBDFA141D7E2A02 ON note (remuneration_id)');
        $this->addSql('CREATE INDEX IDX_CFBDFA14F46CD258 ON note (matiere_id)');
        $this->addSql('CREATE TABLE periode (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(20) NOT NULL, numero INT NOT NULL, annee VARCHAR(20) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE remuneration (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, montant DOUBLE PRECISION NOT NULL, date DATE NOT NULL, type_id INT DEFAULT NULL, enfant_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1969358BC54C8C93 ON remuneration (type_id)');
        $this->addSql('CREATE INDEX IDX_1969358B450D2529 ON remuneration (enfant_id)');
        $this->addSql('CREATE TABLE remuneration_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, family_name VARCHAR(255) NOT NULL, nom VARCHAR(255) NOT NULL, prenom VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE classe ADD CONSTRAINT FK_8F87BF96B3E9C81 FOREIGN KEY (niveau_id) REFERENCES niveau (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE enfant ADD CONSTRAINT FK_34B70CA28F5EA509 FOREIGN KEY (classe_id) REFERENCES classe (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE enfant_family_group ADD CONSTRAINT FK_6A066A75450D2529 FOREIGN KEY (enfant_id) REFERENCES enfant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE enfant_family_group ADD CONSTRAINT FK_6A066A753CEE3234 FOREIGN KEY (family_group_id) REFERENCES family_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT FK_1323A575F384C1CF FOREIGN KEY (periode_id) REFERENCES periode (id)');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT FK_1323A575450D2529 FOREIGN KEY (enfant_id) REFERENCES enfant (id)');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT FK_1323A5751D7E2A02 FOREIGN KEY (remuneration_id) REFERENCES remuneration (id)');
        $this->addSql('ALTER TABLE family_group_user ADD CONSTRAINT FK_97035E463CEE3234 FOREIGN KEY (family_group_id) REFERENCES family_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE family_group_user ADD CONSTRAINT FK_97035E46A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE note ADD CONSTRAINT FK_CFBDFA14450D2529 FOREIGN KEY (enfant_id) REFERENCES enfant (id)');
        $this->addSql('ALTER TABLE note ADD CONSTRAINT FK_CFBDFA14F384C1CF FOREIGN KEY (periode_id) REFERENCES periode (id)');
        $this->addSql('ALTER TABLE note ADD CONSTRAINT FK_CFBDFA141D7E2A02 FOREIGN KEY (remuneration_id) REFERENCES remuneration (id)');
        $this->addSql('ALTER TABLE note ADD CONSTRAINT FK_CFBDFA14F46CD258 FOREIGN KEY (matiere_id) REFERENCES matiere (id)');
        $this->addSql('ALTER TABLE remuneration ADD CONSTRAINT FK_1969358BC54C8C93 FOREIGN KEY (type_id) REFERENCES remuneration_type (id)');
        $this->addSql('ALTER TABLE remuneration ADD CONSTRAINT FK_1969358B450D2529 FOREIGN KEY (enfant_id) REFERENCES enfant (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE classe DROP CONSTRAINT FK_8F87BF96B3E9C81');
        $this->addSql('ALTER TABLE enfant DROP CONSTRAINT FK_34B70CA28F5EA509');
        $this->addSql('ALTER TABLE enfant_family_group DROP CONSTRAINT FK_6A066A75450D2529');
        $this->addSql('ALTER TABLE enfant_family_group DROP CONSTRAINT FK_6A066A753CEE3234');
        $this->addSql('ALTER TABLE evaluation DROP CONSTRAINT FK_1323A575F384C1CF');
        $this->addSql('ALTER TABLE evaluation DROP CONSTRAINT FK_1323A575450D2529');
        $this->addSql('ALTER TABLE evaluation DROP CONSTRAINT FK_1323A5751D7E2A02');
        $this->addSql('ALTER TABLE family_group_user DROP CONSTRAINT FK_97035E463CEE3234');
        $this->addSql('ALTER TABLE family_group_user DROP CONSTRAINT FK_97035E46A76ED395');
        $this->addSql('ALTER TABLE note DROP CONSTRAINT FK_CFBDFA14450D2529');
        $this->addSql('ALTER TABLE note DROP CONSTRAINT FK_CFBDFA14F384C1CF');
        $this->addSql('ALTER TABLE note DROP CONSTRAINT FK_CFBDFA141D7E2A02');
        $this->addSql('ALTER TABLE note DROP CONSTRAINT FK_CFBDFA14F46CD258');
        $this->addSql('ALTER TABLE remuneration DROP CONSTRAINT FK_1969358BC54C8C93');
        $this->addSql('ALTER TABLE remuneration DROP CONSTRAINT FK_1969358B450D2529');
        $this->addSql('DROP TABLE classe');
        $this->addSql('DROP TABLE enfant');
        $this->addSql('DROP TABLE enfant_family_group');
        $this->addSql('DROP TABLE evaluation');
        $this->addSql('DROP TABLE family_group');
        $this->addSql('DROP TABLE family_group_user');
        $this->addSql('DROP TABLE matiere');
        $this->addSql('DROP TABLE niveau');
        $this->addSql('DROP TABLE note');
        $this->addSql('DROP TABLE periode');
        $this->addSql('DROP TABLE remuneration');
        $this->addSql('DROP TABLE remuneration_type');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
