<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260925204047 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE periode_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE periode ADD periode_type_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE periode ADD CONSTRAINT FK_93C32DF36F5017C1 FOREIGN KEY (periode_type_id) REFERENCES periode_type (id)');
        $this->addSql('CREATE INDEX IDX_93C32DF36F5017C1 ON periode (periode_type_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE periode_type');
        $this->addSql('ALTER TABLE periode DROP CONSTRAINT FK_93C32DF36F5017C1');
        $this->addSql('DROP INDEX IDX_93C32DF36F5017C1');
        $this->addSql('ALTER TABLE periode DROP periode_type_id');
    }
}
