<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260925201811 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE enfant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, classe VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, family_name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('ALTER TABLE enfant_family_group ADD CONSTRAINT FK_6A066A75450D2529 FOREIGN KEY (enfant_id) REFERENCES enfant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT FK_1323A575450D2529 FOREIGN KEY (enfant_id) REFERENCES enfant (id)');
        $this->addSql('ALTER TABLE family_group_user ADD CONSTRAINT FK_97035E46A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE note ADD CONSTRAINT FK_CFBDFA14450D2529 FOREIGN KEY (enfant_id) REFERENCES enfant (id)');
        $this->addSql('ALTER TABLE remuneration ADD CONSTRAINT FK_1969358B450D2529 FOREIGN KEY (enfant_id) REFERENCES enfant (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE enfant');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('ALTER TABLE enfant_family_group DROP CONSTRAINT FK_6A066A75450D2529');
        $this->addSql('ALTER TABLE evaluation DROP CONSTRAINT FK_1323A575450D2529');
        $this->addSql('ALTER TABLE family_group_user DROP CONSTRAINT FK_97035E46A76ED395');
        $this->addSql('ALTER TABLE note DROP CONSTRAINT FK_CFBDFA14450D2529');
        $this->addSql('ALTER TABLE remuneration DROP CONSTRAINT FK_1969358B450D2529');
    }
}
