<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260927161805 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE badge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, icone VARCHAR(255) NOT NULL, condition VARCHAR(255) NOT NULL, date_obtention TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, enfant_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FEF0481D450D2529 ON badge (enfant_id)');
        $this->addSql('CREATE TABLE invitation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, token VARCHAR(255) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, family_group_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F11D61A25F37A13B ON invitation (token)');
        $this->addSql('CREATE INDEX IDX_F11D61A23CEE3234 ON invitation (family_group_id)');
        $this->addSql('CREATE TABLE invitation_enfant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, token VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, used BOOLEAN NOT NULL, enfant_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_78B2D768450D2529 ON invitation_enfant (enfant_id)');
        $this->addSql('CREATE TABLE objectif (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, progression INT NOT NULL, termine BOOLEAN NOT NULL, enfant_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E2F86851450D2529 ON objectif (enfant_id)');
        $this->addSql('ALTER TABLE badge ADD CONSTRAINT FK_FEF0481D450D2529 FOREIGN KEY (enfant_id) REFERENCES enfant (id)');
        $this->addSql('ALTER TABLE invitation ADD CONSTRAINT FK_F11D61A23CEE3234 FOREIGN KEY (family_group_id) REFERENCES family_group (id)');
        $this->addSql('ALTER TABLE invitation_enfant ADD CONSTRAINT FK_78B2D768450D2529 FOREIGN KEY (enfant_id) REFERENCES enfant (id)');
        $this->addSql('ALTER TABLE objectif ADD CONSTRAINT FK_E2F86851450D2529 FOREIGN KEY (enfant_id) REFERENCES enfant (id)');
        $this->addSql('ALTER TABLE enfant ADD xp INT NOT NULL');
        $this->addSql('ALTER TABLE enfant ADD niveau INT NOT NULL');
        $this->addSql('ALTER TABLE enfant ADD user_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE enfant ADD CONSTRAINT FK_34B70CA2A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)');
        $this->addSql('CREATE INDEX IDX_34B70CA2A76ED395 ON enfant (user_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE badge DROP CONSTRAINT FK_FEF0481D450D2529');
        $this->addSql('ALTER TABLE invitation DROP CONSTRAINT FK_F11D61A23CEE3234');
        $this->addSql('ALTER TABLE invitation_enfant DROP CONSTRAINT FK_78B2D768450D2529');
        $this->addSql('ALTER TABLE objectif DROP CONSTRAINT FK_E2F86851450D2529');
        $this->addSql('DROP TABLE badge');
        $this->addSql('DROP TABLE invitation');
        $this->addSql('DROP TABLE invitation_enfant');
        $this->addSql('DROP TABLE objectif');
        $this->addSql('ALTER TABLE enfant DROP CONSTRAINT FK_34B70CA2A76ED395');
        $this->addSql('DROP INDEX IDX_34B70CA2A76ED395');
        $this->addSql('ALTER TABLE enfant DROP xp');
        $this->addSql('ALTER TABLE enfant DROP niveau');
        $this->addSql('ALTER TABLE enfant DROP user_id');
    }
}
