<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261008090751 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE reset_password_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, token VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE note ALTER is_remuneration DROP DEFAULT');
        $this->addSql('ALTER TABLE remuneration ADD periode_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE remuneration ADD CONSTRAINT FK_1969358BF384C1CF FOREIGN KEY (periode_id) REFERENCES periode (id)');
        $this->addSql('CREATE INDEX IDX_1969358BF384C1CF ON remuneration (periode_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE reset_password_token');
        $this->addSql('ALTER TABLE note ALTER is_remuneration SET DEFAULT false');
        $this->addSql('ALTER TABLE remuneration DROP CONSTRAINT FK_1969358BF384C1CF');
        $this->addSql('DROP INDEX IDX_1969358BF384C1CF');
        $this->addSql('ALTER TABLE remuneration DROP periode_id');
    }
}
